#!/usr/bin/expect

# http://www.freehttptunnel.com/

set user "ssh"
set server "ssh.freehttptunnel.com"
# check top right corner on the web for the passwd
set passwd "1037"
set port "443"


set timeout 60

spawn ssh -p $port -CND 7070 $user@$server

while {1} {
    expect {
        eof {break}
        "continue connecting (yes/no)?" {send "yes\r"}
        "password:" {send "$passwd\r"; break}
        "*\]" {send "exit\r"}
    }
}
# wait
# close $spawn_id

interact {
    timeout 60 { send " " }
}

