#!/usr/bin/expect

# http://www.chenguiwen.com/free-vpn

set user "vpn1"
set server "ssh.inyun.in"
set passwd "chenguiwen"
set port "22"


set timeout 60

spawn ssh -p $port -CND 7070 $user@$server

while {1} {
    expect {
        eof {break}
        "continue connecting (yes/no)?" {send "yes\r"}
        "password:" {send "$passwd\r"; break}
        "*\]" {send "exit\r"}
    }
}
# wait
# close $spawn_id

interact {
    timeout 60 { send " " }
}

